### ISSUE TITLE
MKG在pretrain时出错

### ISSUE THREAD

**Issue by Tokimitsu40** [zjunlp/MKGformer#40]
您好，我下载了百度网盘上的FB15K数据集，运行bash scripts/pretrain_fb15k-237-image.sh后，在Validation sanity check阶段报了ValueError: mean must have 1 elements if it is an iterable, got 3 错误，想请教一下该如何解决。具体报错信息如下：

Validation sanity check:  50%|█████████████████████████████████████████████████████▌                                                     | 1/2 [00:03<00:03,  3.37s/it]
Traceback (most recent call last):
  File "main.py", line 153, in <module>
    main()
  File "main.py", line 135, in main
    trainer.fit(lit_model, datamodule=data)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 842, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1107, in run_sanity_check
    self.run_evaluation()
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 949, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/user1/chenchi/MKGformer/MKG/data/data_module.py", line 168, in __call__
    aux_img = aux_processor(images=aux_img, return_tensors='pt')['pixel_values'].squeeze()
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/models/clip/processing_clip.py", line 104, in __call__
    image_features = self.image_processor(images, return_tensors=return_tensors, **kwargs)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 552, in __call__
    return self.preprocess(images, **kwargs)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/models/clip/image_processing_clip.py", line 316, in preprocess
    images = [
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/models/clip/image_processing_clip.py", line 317, in <listcomp>
    self.normalize(image=image, mean=image_mean, std=image_std, input_data_format=input_data_format)
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 622, in normalize
    return normalize(
  File "/home/user1/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/image_transforms.py", line 386, in normalize
    raise ValueError(f"mean must have {num_channels} elements if it is an iterable, got {len(mean)}")
ValueError: mean must have 1 elements if it is an iterable, got 3

**Comment by flow3rdown** [comment]
您好，请问您是否正确下载了相关数据集？目测是子图处理部分出现了问题

**Comment by Tokimitsu40** [comment]
您好，我下载的是您在百度网盘上传的FB15k-images.tar.gz文件，解压两次之后解压出了FB15k-images文件夹，然后放在MKG\dataset文件夹。（MKG\dataset文件夹中原本就有的FB15k-images文件夹被我删除了）

**Comment by flow3rdown** [comment]
您贴的报错中显示在处理某个子图的时候出现了问题:
```bash
File "/home/user1/chenchi/MKGformer/MKG/data/data_module.py", line 168, in call
aux_img = aux_processor(images=aux_img, return_tensors='pt')['pixel_values'].squeeze()
```
可以麻烦您定位一下具体是哪个子图出现的问题吗？另外可以确认下使用的`process`是否是正确的。

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by Tokimitsu40** [comment]
您好，之前在aux_img = aux_processor(images=aux_img, return_tensors='pt')['pixel_values'].squeeze()这句话之前print了一下报错文件的位置，把报错的文件夹删掉了，现在可以通过Validation sanity check阶段阶段了。但是在训练时又在rcnn_img = rcnn_processor(images=rcnn_img, return_tensors='pt')['pixel_values'].squeeze()这句话报错，删除多个报错文件夹以后依然报错,我先再排查一下。

**Comment by Tokimitsu40** [comment]
您好，已经解决了，数据集里有一些1*1像素的图像会报错，全部删除以后就可以跑通了，谢谢您的解答。

**Comment by wyZhang016** [comment]
> 您好，已经解决了，数据集里有一些1*1像素的图像会报错，全部删除以后就可以跑通了，谢谢您的解答。

您好，我在wn18-img上运行代码出现了和您一样的问题，请问您是如何删除这些1*1像素的图片的

**Comment by wzl0422** [comment]
> 您好，已经解决了，数据集里有一些1*1像素的图像会报错，全部删除以后就可以跑通了，谢谢您的解答。

您好，具体时指哪些图片？怎么解决的？求指教

**Comment by Tokimitsu40** [comment]
> > 您好，已经解决了，数据集里有一些1*1像素的图像会报错，全部删除以后就可以跑通了，谢谢您的解答。
> 
> 您好，具体时指哪些图片？怎么解决的？求指教

你可以写一个python脚本把数据集扫一下，我记得有一些是1 * 1的，有一些是1 * 10左右的，都会报错，大概把大小在10*10以下的图片都删掉就能解决了。

**Comment by ZuoMM-f** [comment]
#52 请问您在运行MKG任务时是否遇到这个问题
