### ISSUE TITLE
assert logits.shape == labels.shape

### ISSUE THREAD

**Issue by wyZhang016** [zjunlp/MKGformer#41]
最近在跑代码的时候出现下面的错误
Traceback (most recent call last):
  File "main.py", line 169, in <module>
    main()
  File "main.py", line 151, in main
    trainer.fit(lit_model, datamodule=data)
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 842, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1107, in run_sanity_check
    self.run_evaluation()
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 962, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/home/E/anaconda3/envs/MKGC/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
  File "/home/E/python/MKGformer-main/MKG/lit_models/transformer.py", line 105, in validation_step
    result = self._eval(batch, batch_idx)
  File "/home/E/python/MKGformer-main/MKG/lit_models/transformer.py", line 96, in _eval
    assert logits.shape == labels.shape
AssertionError
出现问题是在pretrain步骤，请问出现问题的原因可能是什么。我该如何解决，谢谢！

**Comment by flow3rdown** [comment]
您好，请问您有修改代码或数据集吗，`logits`和`labels`的shape不一致，您可以查看一下它们两个具体的shape

**Comment by wyZhang016** [comment]
代码和数据集目前我没有动过，logits的shape是19300而labels的是256

> 您好，请问您有修改代码或数据集吗，`logits`和`labels`的shape不一致，您可以查看一下它们两个具体的shape

**Comment by wyZhang016** [comment]
> 您好，请问您有修改代码或数据集吗，`logits`和`labels`的shape不一致，您可以查看一下它们两个具体的shape

您好，当我重新下载文献和数据库时，发现问题已经解决，目前可以正常pretrain，感谢您提供的帮助，谢谢
